version: "3"

services:
  room_reservation:
    container_name: room_reservation
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
        - ./.env
